name: myenv
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - faiss-cpu
  - pip
  - pip:
      - -r file:requirements.txt

  # Note:
  # To install this dependencies 
  # conda env create -f environment.yml
  # then activate the environment
  # conda activate myenv

